# Generated by Django 4.1 on 2022-09-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=32)),
                ('book_category', models.CharField(max_length=32)),
                ('book_author_name', models.CharField(max_length=32)),
                ('book_description', models.CharField(max_length=32)),
                ('book_price', models.IntegerField()),
                ('number_of_pages', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
