# Generated by Django 4.1.4 on 2022-12-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Password', models.CharField(max_length=32)),
                ('Mobile_no', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
