# Generated by Django 4.1.6 on 2023-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=32)),
                ('Mobile_no', models.BigIntegerField(max_length=10)),
                ('Occupation', models.CharField(max_length=40)),
            ],
        ),
    ]
