# Generated by Django 4.1.6 on 2023-02-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0002_alter_registertable_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='aadharcardtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharnumber', models.BigIntegerField()),
                ('firstname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phonenumber', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('cast', models.CharField(max_length=30)),
                ('gender', models.IntegerField(choices=[{'0', 'male'}, {'female', '1'}])),
                ('document', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='feedbacktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regid', models.IntegerField()),
                ('feedbackdesk', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='policytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyname', models.CharField(max_length=30)),
                ('policydetails', models.TextField()),
                ('policytype', models.IntegerField()),
                ('policyphoto', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.AddField(
            model_name='registertable',
            name='role',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registertable',
            name='status',
            field=models.IntegerField(choices=[{'0', 'inactive'}, {'active', '1'}], null=True),
        ),
        migrations.AlterField(
            model_name='registertable',
            name='Mobile_no',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='applicationtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('policyid', models.BigIntegerField()),
                ('status', models.IntegerField()),
                ('regid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goverment_app.registertable')),
            ],
        ),
        migrations.AddField(
            model_name='registertable',
            name='aadharid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goverment_app.aadharcardtable'),
        ),
    ]
