# Generated by Django 4.1.6 on 2023-02-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0003_aadharcardtable_feedbacktable_policytable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadharcardtable',
            name='middlename',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicationtable',
            name='policyid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goverment_app.policytable'),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='regid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goverment_app.registertable'),
        ),
    ]
