# Generated by Django 4.1.6 on 2023-02-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0004_alter_aadharcardtable_middlename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytable',
            name='policyCast',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policytable',
            name='policyGender',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
