# Generated by Django 4.1.6 on 2023-02-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0007_alter_policytable_policyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtable',
            name='policyid',
        ),
        migrations.DeleteModel(
            name='policytable',
        ),
    ]
