# Generated by Django 4.1.6 on 2023-02-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0008_remove_applicationtable_policyid_delete_policytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='policytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyname', models.CharField(max_length=120)),
                ('policydetails', models.TextField()),
                ('policytype', models.CharField(max_length=30)),
                ('policyphoto', models.ImageField(upload_to='media')),
                ('policyAgency', models.CharField(max_length=30)),
                ('policyCast', models.CharField(max_length=20, null=True)),
                ('policyTargetAudience', models.CharField(max_length=30)),
                ('policyEligibleCastes', models.CharField(max_length=30)),
                ('policyApplicableState', models.CharField(max_length=30)),
                ('policyResidenceArea', models.CharField(max_length=30)),
                ('policyDisabilityStatus', models.CharField(max_length=30)),
                ('policyMinorityStatus', models.CharField(max_length=30)),
                ('policyBPLStatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='applicationtable',
            name='policyid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goverment_app.policytable'),
        ),
    ]
