# Generated by Django 4.1.6 on 2023-02-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0010_policytable_policyurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policytable',
            name='policyCast',
        ),
    ]
