# Generated by Django 4.1.6 on 2023-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0011_remove_policytable_policycast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytable',
            name='policyAgency',
            field=models.CharField(max_length=100),
        ),
    ]
