# Generated by Django 4.1.7 on 2023-02-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0015_alter_policytable_policyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytable',
            name='policyAgency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policyApplicableState',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policyBPLStatus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policyDisabilityStatus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policyEligibleCastes',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policyMinorityStatus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policyResidenceArea',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policyTargetAudience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policydetails',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policyname',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policyphoto',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='policytype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
