# Generated by Django 4.1.7 on 2023-03-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0016_alter_policytable_policyagency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadharcardtable',
            name='BPLStatus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aadharcardtable',
            name='DisabilityStatus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aadharcardtable',
            name='MinorityStatus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aadharcardtable',
            name='ResidenceArea',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
