# Generated by Django 4.1.7 on 2023-03-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0018_alter_aadharcardtable_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadharcardtable',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
