# Generated by Django 4.1.7 on 2023-03-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0019_alter_aadharcardtable_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadharcardtable',
            name='aadharnumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aadharcardtable',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aadharcardtable',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
