# Generated by Django 4.1.7 on 2023-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0020_alter_aadharcardtable_aadharnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='feedbackdesk',
            field=models.TextField(null=True),
        ),
    ]
