# Generated by Django 4.1.7 on 2023-03-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0021_feedbacktable_email_feedbacktable_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
