# Generated by Django 4.1.7 on 2023-03-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment_app', '0022_feedbacktable_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='regid',
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
