# Generated by Django 4.1.3 on 2022-11-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='female_actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('f_dob', models.DateField(max_length=30)),
                ('f_pic', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='male_actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=30)),
                ('m_dob', models.DateField(max_length=30)),
                ('m_pic', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='movie_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=30)),
                ('movie_pic', models.ImageField(upload_to='photos')),
                ('movie_description', models.TextField()),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie_category')),
                ('female_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.female_actor')),
                ('male_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.male_actor')),
            ],
        ),
    ]
